--liquibase formatted sql
--changeset test:1
CREATE TABLE FUNDS (
  ID                 NUMERIC(*, 0)  NOT NULL,
  CODE               NUMERIC(*, 0),
  NAME               VARCHAR2(255) NOT NULL
);

ALTER TABLE FUNDS
  ADD CONSTRAINT PK_FUNDS_REC_ID PRIMARY KEY (ID);

CREATE SEQUENCE FUNDS_SEQ
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 CACHE 20;

--changeset test:2
CREATE TABLE COMPANIES (
  ID                 NUMERIC(*, 0)  NOT NULL,
  CODE               NUMERIC(*, 0),
  NAME               VARCHAR2(255) NOT NULL
);

ALTER TABLE COMPANIES
  ADD CONSTRAINT PK_COMPANIES_REC_ID PRIMARY KEY (ID);

ALTER TABLE COMPANIES
  ADD CONSTRAINT COMPANIES_NAME UNIQUE (NAME);

CREATE SEQUENCE COMPANIES_SEQ
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 CACHE 20;

--changeset test:3
CREATE TABLE BOURSES (
  ID                 NUMERIC(*, 0)  NOT NULL,
  CODE               NUMERIC(*, 0),
  NAME               VARCHAR2(255) NOT NULL
);

ALTER TABLE BOURSES
  ADD CONSTRAINT PK_BOURSES_REC_ID PRIMARY KEY (ID);

CREATE SEQUENCE BOURSES_SEQ
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 CACHE 20;

--changeset test:4
CREATE TABLE ASSETS (
  ID                 NUMERIC(*, 0)  NOT NULL,
  ASSET_NAME         VARCHAR2(255),
  COMPANY_ID         NUMBER(19) NOT NULL
);

ALTER TABLE ASSETS
  ADD CONSTRAINT PK_ASSETS_REC_ID PRIMARY KEY (ID);

ALTER TABLE ASSETS
  ADD CONSTRAINT FK_COMPANY_ID FOREIGN KEY ( COMPANY_ID )
REFERENCES COMPANIES(id);

CREATE SEQUENCE ASSETS_SEQ
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 CACHE 20;

--changeset test:5
CREATE TABLE BOURSE_ASSETS (
  ID                 NUMERIC(*, 0)  NOT NULL,
  ASSET_ID           NUMBER(19) NOT NULL,
  BOURSE_ID          NUMBER(19) NOT NULL
);

ALTER TABLE BOURSE_ASSETS
  ADD CONSTRAINT PK_BOURSE_ASSETS_REC_ID PRIMARY KEY (ID);

ALTER TABLE BOURSE_ASSETS
  ADD CONSTRAINT FK_ASSET_ID FOREIGN KEY ( ASSET_ID )
REFERENCES ASSETS(id);

ALTER TABLE BOURSE_ASSETS
  ADD CONSTRAINT FK_BOURSE_ID FOREIGN KEY ( BOURSE_ID )
REFERENCES BOURSES(id);

CREATE SEQUENCE BOURSE_ASSETS_SEQ
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 CACHE 20;

--changeset test:6
CREATE TABLE FUNDS_PORTFOLIO (
  ID                 NUMERIC(*, 0)  NOT NULL,
  FUND_ID            NUMBER(19) NOT NULL,
  ASSET_ID           NUMBER(19) NOT NULL,
  VALUE              NUMERIC(*, 0),
  SHARES             NUMERIC(*, 0),
  REPORT_DATE        DATE
);

ALTER TABLE FUNDS_PORTFOLIO
  ADD CONSTRAINT PK_FUNDS_PORTFOLIO_REC_ID PRIMARY KEY (ID);

ALTER TABLE FUNDS_PORTFOLIO
  ADD CONSTRAINT FK_FUND_ID FOREIGN KEY ( FUND_ID )
REFERENCES FUNDS(id);

ALTER TABLE FUNDS_PORTFOLIO
  ADD CONSTRAINT FK_FUND_ASSET_ID FOREIGN KEY ( ASSET_ID )
REFERENCES ASSETS(id);

CREATE SEQUENCE FUNDS_PORTFOLIO_SEQ
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 CACHE 20;

--changeset test:7
/*CREATE TABLE CURRENCIES (
  ID                NUMERIC(*, 0)  NOT NULL,
  CODE              VARCHAR2(255)
);

ALTER TABLE CURRENCIES
  ADD CONSTRAINT PK_BOURSE_ASSETS_VALUES_REC_ID PRIMARY KEY (ID);*/

--changeset test:8
CREATE TABLE BOURSE_ASSETS_VALUES (
  ID                 NUMERIC(*, 0)  NOT NULL,
  BOURSE_ASSET_ID    NUMBER(19) NOT NULL,
  VALUE              DOUBLE PRECISION,
  CURRENCY           VARCHAR2(255),
  INFO_DATE          DATE
);

ALTER TABLE BOURSE_ASSETS_VALUES
  ADD CONSTRAINT PK_BOURSE_ASSETS_VALUES_REC_ID PRIMARY KEY (ID);

ALTER TABLE BOURSE_ASSETS_VALUES
  ADD CONSTRAINT FK_BOURSE_ASSET_ID FOREIGN KEY ( BOURSE_ASSET_ID )
REFERENCES BOURSE_ASSETS(id);

/*ALTER TABLE BOURSE_ASSETS_VALUES
  ADD CONSTRAINT BOURSE_ASSETS_VALUES_UNIQUE UNIQUE (BOURSE_ASSET_ID, INFO_DATE);*/

CREATE SEQUENCE BOURSE_ASSETS_VALUES_SEQ
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 CACHE 20;

/*
--changeset test:8
CREATE TABLE CURRENCY_CONVERTER (
  ID                 NUMERIC(*, 0)  NOT NULL,
  CURRENCY    NUMBER(19) NOT NULL,
  VALUE              DOUBLE PRECISION,
  CURRENCY           VARCHAR2(255),
  INFO_DATE          DATE
);*/
